= Iapetus
Team 3161
v0.1, 10 February 2014

== What is this?
Iapetus is the working name for FRC 3161's robot code for the 2014 season. For
more information about the team, or the robot for which this code was written,
please visit http://team3161.ca.

== Introduction
Iapetus marks the first robot code system built by Team 3161 with the express
intention of producing reusable code, both for Team 3161 and others.

The package ca.team3161.iapetus contains robot-specific code.
The other packages (ca.team3161.lib.*) are intended as reusable modules.
Each such class has at least skeleton documentation explaining its
purpose, but for ease of reference and a high-level overview, this
document will explain the concepts behind the Iapetus libraries.

== Overview
=== IO (ca.team3161.lib.utils.io)
==== DriverStationLCD
Provides a nice wrapper overtop of FIRST's provided DriverStationLCD
class.

=== Controls (ca.team3161.lib.utils.controls)
==== Gamepad
An interface defining a physical gamepad type controller. These are
expected to have two thumbsticks, a directional pad, and an assortment
of buttons. They may have additional functionality as well, but this
is the minimal set. The thumbsticks' Y-axes may also be inverted.

==== Joystick
A thin wrapper overtop of FIRST's provided Joystick class, offering
deadzone filtering.

==== LogitechDualAction
A Gamepad implementation modelling the Logitech DualAction USB gamepad.
In addition to the methods required by the Gamepad interface, this
class offers convenience methods to check the "bumpers" and "triggers"
(shoulder buttons) on the controller. It also offers deadzone filtering,
so that very small values returned by the thumbsticks can be ignored, in
case the gamepad is not properly zeroed, or has damaged springs, etc.

=== General utilities (ca.team3161.lib.utils)
==== Assert
==== Utils

=== PID (ca.team3161.lib.robot.pid)
==== AnglePidSrc
==== EncoderPidSrc
==== GyroPidSrc
==== PID
==== PIDSrc
==== PIDulum
==== PotentiometerPidSrc

=== Robot subsystems (ca.team3161.lib.robot)
==== Drivetrain
==== PIDDrivetrain
==== ResourceTracker
==== Subsystem
==== ThreadedAutoRobot

=== Team 3161's 2014 robot (ca.team3161.iapetus)
==== Constants
==== Iapetus
==== Shooter

